Highlighted difference between IPA and app binary
OWASP/owasp-mstg pull request #1811
Opened 2020-08-30 08:06 UTC by cpholguera

This PR closes #1794

2020-08-31 18:29 UTC, TheDauntless requested changes
One small change for me and it can be merged :)

2020-08-31 18:29 UTC, TheDauntless commented on Document/0x05c-Reverse-Engineering-and-Tampering.md
> +Refer to the [Release Notes](https://frida.re/news/2020/06/29/frida-12-10-released/ "Frida 12.10") for more details. To learn more about all options for advanced usage, check the [documentation in th
```suggestion
Refer to the [Release Notes](https://frida.re/news/2020/06/29/frida-12-10-released/ "Frida 12.10") for more details. To learn more about all options for advanced usage, check the [documentation on the official Frida website](https://frida.re/docs/frida-trace/ "documentation").
```

2020-09-01 02:15 UTC, sushi2k approved these changes
Very cool PR. Thanks for closing so many issues at once :-)

2020-09-01 06:12 UTC, TheDauntless approved these changes

2020-09-01 06:14 UTC, merged