added changes from 1855
OWASP/owasp-mstg pull request #1864
Opened 2020-12-04 16:54 UTC by cpholguera

to be merged instead of #1855 due to inactivity and different location of content.

2020-12-05 00:56 UTC, sushi2k requested changes
One tiny change :-)

2020-12-05 00:56 UTC, sushi2k commented on Document/0x08-Testing-Tools.md
> +- [`frida-ps`](https://www.frida.re/docs/frida-ps/ "frida-ps") to obtain a list of all apps (or processes) running on the device including their names, identifiers and PDIs.
```suggestion
- [`frida-ps`](https://www.frida.re/docs/frida-ps/ "frida-ps") to obtain a list of all apps (or processes) running on the device including their names, identifiers and PIDs.
```

2020-12-08 12:02 UTC, cpholguera commented
Thanks @sushi2k, done!

2020-12-22 12:32 UTC, sushi2k approved these changes
LGTM

2020-12-22 12:32 UTC, merged