Add tool SCRCPY
OWASP/owasp-mstg pull request #1901
Opened 2021-04-17 06:56 UTC by righettod

Hi,

This PR cover the proposal described in #1898 

- [x] Your contribution is written in the 2nd person (e.g. you)
- [x] Your contribution is written in an active present form for as much as possible.
- [x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [x] Your contribution has proper formatted markdown and/or code
- [x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

Thanks a lot in advance 😃

2021-04-17 07:03 UTC, righettod commented
Link check failed but it is not due to the PR because I have checked twice that all added links are valid 😢

2021-04-18 06:25 UTC, cpholguera requested changes
Only one little suggestion :)

2021-04-18 06:25 UTC, cpholguera commented on Document/0x08-Testing-Tools.md
> +[Scrcpy](https://github.com/Genymobile/scrcpy "Scrcpy") provides display and control of Android devices connected on USB (or [over TCP/IP](https://www.genymotion.com/blog/open-source-project-scrcpy-n
```suggestion
[Scrcpy](https://github.com/Genymobile/scrcpy "Scrcpy") provides display and control of Android devices connected over USB (or [TCP/IP](https://www.genymotion.com/blog/open-source-project-scrcpy-now-works-wirelessly/ "Scrcpy now works wirelessly")). It does not require any root access and it works on GNU/Linux, Windows and macOS.
```

2021-04-18 06:33 UTC, cpholguera commented
same here, I've changed

This PR cover the proposal described in #1898 

to

This PR closes #1898 

to let GitHub do its magic ✨

2021-04-18 07:40 UTC, righettod commented
I have commited your suggestion, it is great 😃

2021-04-18 12:47 UTC, cpholguera approved these changes
Thanks for adding this @righettod!

2021-04-18 12:48 UTC, merged

2021-04-18 14:25 UTC, righettod commented
You are welcome @cpholguera , it is always a pleasure to contribute to this amazing project 💯 and exchange with you 👍

2021-04-18 15:09 UTC, cpholguera commented
Now that you're into the cleanup mood, which we really appreciate, maybe you'd like to take over this one: https://github.com/OWASP/owasp-mstg/issues/1839

What do you think? Maybe #1838 as well? If yes, please let me know in order to assign them to you.

2021-04-18 15:34 UTC, righettod commented
Yes, can assign it to me, I will use the following searches as identification points:
- [Needle](https://github.com/OWASP/owasp-mstg/search?q=needle)
- [Drozer](https://github.com/OWASP/owasp-mstg/search?q=drozer)

I will try to work on it coming tuesday, otherwise next week end 😃

2021-04-18 19:54 UTC, cpholguera commented
Thank you very much @righettod!