Added instructions explaining how to move certificate from user to root store
OWASP/owasp-mstg pull request #1915
Opened 2021-06-23 09:58 UTC by DemanNL

Added instructions explaining how to move the burp certificate from user to root store.

You can also add alternative certificate installation instructions. The current instructions download the cert outside android VM, push it and install it. This can all be done from within the Android VM as well.

The instructions would be as followed:

1. Start Burp and configure your Android VM Wi-Fi settings to use Burp proxy.
2. Visit http://burp, and download the certificate.
3. Rename the certificate to cacert.cer.
4. Open the file and you will be prompted to confirm installation of the certificate.

Let me know what you think about the alternative instructions as well and if it would fit in the document or not.

2021-07-12 07:48 UTC, sushi2k commented on Document/0x05b-Basic-Security_Testing.md
> +4. Reboot the Android VM.
This is unfortunately already outdated and will only work for Android versions below 7.0. We should put in a sentence instead saying that Network Security Configuration is enforcing that user installed CAs are not trusted by default anymore. 
There is the manual option of getting the Burp CA into the System truststore (Bypassing the Network Security Configuration) and the one we described in the MSTG in "Bypassing the Network Security Configuration"

Do you want to re-structure the paragraph instead?

2021-07-12 07:48 UTC, sushi2k requested changes
See comment

2021-08-05 22:20 UTC, sushi2k commented
Just updated my comment, apologies was referring to hardware devices originally not to VMs; I changed my comment. Please have a look! 
Thank you @DemanNL

2021-08-25 11:01 UTC, sushi2k commented
Got update from proxy77 in Slack: "it works for me in android version 10 (geneymotion custom device)"

2021-09-02 12:36 UTC, cpholguera commented
I was going thought the PRs, here only this comment https://github.com/OWASP/owasp-mstg/pull/1915#discussion_r667701885 is open, right? @DemanNL please let us know when you address that to make a final review. Thanks in advance!

2021-09-03 11:49 UTC, DemanNL reviewed
Added on which VM this was tested. However I'm sure this works on any rooted machine.

2021-09-03 11:50 UTC, DemanNL commented
> 
> 
> I was going thought the PRs, here only this comment [#1915 (comment)](https://github.com/OWASP/owasp-mstg/pull/1915#discussion_r667701885) is open, right? @DemanNL please let us know when you address that to make a final review. Thanks in advance!

@cpholguera is everything okay now?

2022-06-27 08:44 UTC, TheDauntless approved these changes

2022-06-27 12:25 UTC, sushi2k approved these changes

2022-06-27 13:36 UTC, merged