0x06b - Upgrade Jailbreak section
OWASP/owasp-mstg pull request #1943
Opened 2021-10-15 11:04 UTC by cpholguera

- update basic testing setup
- upgrade the jailbreak section to make it more up-to-date and at the same time timeless (include most complete sources for jailbreakable devices/versions)
- include links to other relevant chapters

2022-01-23 14:55 UTC, TheDauntless requested changes
A few small changes and it's good to go :)

2022-01-23 14:55 UTC, TheDauntless commented on Document/0x06b-Basic-Security-Testing.md
> +We definitely recommend you to have a jailbroken iPhone or iPad for testing. These devices allow root access and tool installation, making the security testing process more straightforward. See the n
```suggestion
We recommend having a jailbroken iPhone or iPad for testing. These devices allow root access and tool installation, making the security testing process more straightforward. See the next section ["Getting Privileged Access"](#getting-privileged-access) for more information.
```

2022-01-23 14:55 UTC, TheDauntless commented on Document/0x06b-Basic-Security-Testing.md
> +- Untethered jailbreaks are the most popular choice for end users because they need to be applied only once, after which the device will be permanently jailbroken. They are very rare and usually bene
Isn't the fact that it's untethered because there are additional vulnerabilities that allow you to write persistent code somewhere that is not part of the secure boot chain? (rather than the fact that the vulnerability itself is in HW, because Checkra1n is also in bootrom, but non persistent)

2022-01-23 14:55 UTC, TheDauntless commented on Document/0x06b-Basic-Security-Testing.md
> +Also consider getting one or multiple spare devices (which you will be updating with every major iOS release) and wait for new jailbreak software to be released publicly (see next section). Apple is
```suggestion
Also consider getting one or more spare devices (which you will be updating with every major iOS release) and wait for new jailbreak software to be released publicly (see next section). Apple is usually quick to release a patch once a jailbreak has been released publicly, so you have only a couple of days to downgrade to the affected iOS version and apply the jailbreak.
```

2022-01-23 14:55 UTC, TheDauntless commented on Document/0x06b-Basic-Security-Testing.md
> +Other sources that have been and might still be reliable include:
```suggestion
Other sources that have been, and might still be, reliable include:
```

2022-01-23 14:55 UTC, TheDauntless commented on Document/0x06b-Basic-Security-Testing.md
>  - [The iPhone Wiki](https://www.theiphonewiki.com/ "The iPhone Wiki")
```suggestion
```
This one isn't maintained anymore.

2022-01-23 14:55 UTC, TheDauntless commented on Document/0x06b-Basic-Security-Testing.md
> +The UDID is a 40-digit unique sequence of letters and numbers to identify an iOS device. You can find the UDID of your iOS device on macOS Catalina onwards in the Finder app, as iTunes is not availab
```suggestion
The UDID is a 40-digit unique sequence of letters and numbers to identify an iOS device. You can find the UDID of your iOS device on macOS Catalina onwards in the Finder app, as iTunes is not available anymore in Catalina. Select the connected iOS device in Finder and click on the information under the name of the iOS device to iterate through it. Besides the UDID, you can find the serial number, IMEI and other useful information.
```

2022-01-23 15:43 UTC, TheDauntless approved these changes
LGTM! 🍀

2022-01-25 11:37 UTC, cpholguera commented on Document/0x06b-Basic-Security-Testing.md
> +- Untethered jailbreaks are the most popular choice for end users because they need to be applied only once, after which the device will be permanently jailbroken. They are very rare and usually bene
```suggestion
- Untethered jailbreaks are the most popular choice for end users because they need to be applied only once, after which the device will be permanently jailbroken. They are usually rare and benefit from vulnerabilities allowing an exploit to write persistent code on the device. An example is the [limera1n exploit](https://www.theiphonewiki.com/wiki/Limera1n "limera1n exploit") which directly affected the BootROM of the iPhone 4 and iPad 1.
```

2022-01-25 17:38 UTC, merged